language: go
os:
- linux
go:
- 1.10.1
sudo: required
script:
- go get -t ./...
- go generate
- go test ./...
- go get github.com/karalabe/xgo
- |
  # Get the full go repo url
  REPO=$(pwd |  rev | cut -d'/' -f-3 | rev)

  # Get the name of the app
  APP="${PWD##*/}"

  # Get this tag as the version
  VERSION=$(git describe --abbrev=0 --tags)

  # Ensure a fresh build folder
  rm -rf build && mkdir build
  # Compile
  xgo \
    -dest build/ \
    -buildmode=plugin  \
    --targets=darwin/amd64,freebsd/386,freebsd/amd64,freebsd/arm,linux/386,linux/amd64,linux/arm64  \
    --ldflags "-X plugin.version=${VERSION}" \
    $REPO

  # Package
  cd build
  # For each compiled binary, we're repackaging it in a zip with the architecture name, and
  # renaming the binary to the app name
  for FILE in $(ls .); do
    mv $FILE $APP.so
    tar cvzf ${FILE}.tgz $APP.so
    rm -f $APP.so
  done
  cd ..

# Deploy to Github release on tags
deploy:
  provider: releases
  api_key:
    secure: XKXamWW4fttri6OE79mGRrOtuJm7kHXjJJzumloYAtGQRekUM3WA+MM+6nfU1LzrjSJyjMnHhxZD0MRCBkfsVOwuPTPMSMG6gLhbS5ctf5ipDfKWHAxyBKPvc0Z68Cmc5GoxnQIZkPYczv5juCq382hwH+8Y1V/jHHMDUa918QbrjnU67ETWT+Ci9g4lSbjFiz8cjt9pgkZV2V/AwSVufrIAolqu5yOv+ZxUWm8MURGIKrVk5ftRA1lEVWoCfdC5hkRDMpXoiomZ6hLxBpqWEZJ1XkNDYtL9GEpG44/0T4be4GvcBtaynyRoCx0pLCzzcVrt3r3UCP1KeL3s5mCl1jHiBiNmqtwgVgti6RIyJgSe7/hBIWpe8aqGUAfSI3IpcjOB7NsbOXyomvhdSqJhA7xWzeX9ZGaYCooMyIa7OfrA8uQw0TQbs2I6JwXPhWC5sWspF8DVfzeigXIuJ/dcyw3O74GwA84uOPji8q8NoEyddFDFnrnD+mDmqWe3SbhUtUpYHVa7CxP+iZV1zDADG7fXT5oreXVY2dYgxj7vBAgMbPM4JsBX/RudKBz/S8dRuHlCr2xBaYPVBTaAFtLEEaqjbl+6tuoB4oEuHpSWXdRF3lp0V9tjdQrlf0LeVaaxR5q1ueGRct/r1zc7MLTsrRBMUcpIKtSax+0MHVL5xT4=
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
